### ISSUE TITLE
Merge QtYarp in YARP

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#219]
Tracker bug for merging qtyarp in yarp.

- [x] Bugs open in QtYarp
  - [x] robotology-playground/qtyarp#2 [Manager] Missing icons -> #268
  - [x] robotology-playground/qtyarp#16 Window menus do not open at the first click -> #282
  - [x] robotology-playground/qtyarp#23 No message when yarpserver is not detected -> #289
  - [x] robotology-playground/qtyarp#24 QtYARPView help documentation non correct View -> #290
  - [x] robotology-playground/qtyarp#31 There is confusion on what you can do with localhost and with a normal node (through yarprun). ->  #297
  - [x] robotology-playground/qtyarp#35 QtYarpScope Quit menu item does not work -> #301
  - [x] robotology-playground/qtyarp#37 QtYARPManager crashes -> #303
- [x] Decisions to take:
  - [x] Where the guis should be in the source tree
  - [x] If we want to move some code around (and eventually move it)
  - [x] If qt and gtk guis should be co-installable or not, and if not how to handle this.
- [x] Import qtyarp (possibly with the whole history)
- [x] Fix CMake
- [x] Fix READMEs, documentation, wikis, etc.
- [x] Fix packaging scripts

**Comment by traversaro** [comment]
We have also to update:
 * [ ] The Linux dependecies wiki page http://wiki.icub.org/wiki/Linux:_dependencies

**Comment by drdanz** [comment]
Packaging scripts are fixed and documentation should be updated.

Closing (finally)

**Comment by traversaro** [comment]
The  Linux dependencies wiki page is still not updated.. we can remove it or update it :
http://wiki.icub.org/wiki/Linux:_dependencies

**Comment by drdanz** [comment]
+1 for removing that page

**Comment by traversaro** [comment]
+1 Also for me.  Hardcore user interested in this can be pointed to https://github.com/robotology/icub-packaging/blob/3f1dc3b202108724d5682c2762e74b7a9f02894a/linux/config.sh#L22 . 
(Reminder: remove also the input links: from http://wiki.icub.org/wiki/Special:WhatLinksHere/Linux:_dependencies )

**Comment by traversaro** [comment]
Updated http://wiki.icub.org/wiki/Linux:_dependencies , but we should review also http://wiki.icub.org/wiki/List_of_Dependencies
