### ISSUE TITLE
Allow lambdas as callback

### ISSUE THREAD

**Issue by drdanz** [robotology/yarp#2404]
At the moment, all the callback mechanisms in YARP require writing a class that implement some interface, just to have a method that is called as callback. It would be a lot better to be able to pass lambdas to these functions.
Also in some cases it would be useful to receive a `std::future` in reply

I'll keep a list here, and link to the related issues and PRs

- [ ] `yarp::os::Port::setReader()` requires a `yarp::os::PortReader`

  * [`yarp::os::Port::setReader()`](http://www.yarp.it/git-master/classyarp_1_1os_1_1Port.html#a1dd5e79319a03bc62d806dddc7e3df96)
  * #1927
  * #1945

- [ ] `yarp::os::Port::getReport()` and `Port::setReporter()` require a `yarp::os::PortReport`

  * [`yarp::os::Port::getReport()`](http://www.yarp.it/git-master/classyarp_1_1os_1_1Port.html#ac3a543e6e63d83856c2d2b96a59a4c20)
  * [`yarp::os::Port::setReporter()`](http://www.yarp.it/git-master/classyarp_1_1os_1_1Port.html#a8789e56ef1cbe51394340a6738682ab3)
  * #2045

- [ ] `yarp::os::Port::write()` requires a `yarp::os::PortWriter`

  * [`yarp::os::Port::write()` 1/2](http://www.yarp.it/git-master/classyarp_1_1os_1_1Port.html#a1b49511d808f5731e2f7cf9e9831ff5e)
  * [`yarp::os::Port::write()` 2/2](http://www.yarp.it/git-master/classyarp_1_1os_1_1Port.html#a23a872378641ddc6f6221067e6ff58ef)
  * (related #2403)

- [ ] `yarp::os::BufferedPort::useCallback()` requires a `yarp::os::TypedReaderCallback`

  * [`yarp::os::BufferedPort::useCallback()`](http://www.yarp.it/git-master/classyarp_1_1os_1_1BufferedPort.html#aea0f25e2dae3a8f5b26ad079ffdb2735)
